
// dispatch homeland
export const FETCH_HOMELAND_REQUEST = 'FETCH_HOMELAND_REQUEST'
export const FETCH_HOMELAND_ERROR = 'FETCH_HOMELAND_ERROR'
export const FETCH_HOMELAND_SUCCESS = 'FETCH_HOMELAND_SUCCESS'

// dispatch disadvantages
export const FETCH_DISADVANTAGES_REQUEST = 'FETCH_DISADVANTAGES_REQUEST'
export const FETCH_DISADVANTAGES_ERROR = 'FETCH_DISADVANTAGES_ERROR'
export const FETCH_DISADVANTAGES_SUCCESS = 'FETCH_DISADVANTAGES_SUCCESS'

// dispatch advantages
export const FETCH_ADVANTAGES_REQUEST = 'FETCH_ADVANTAGES_REQUEST'
export const FETCH_ADVANTAGES_ERROR = 'FETCH_ADVANTAGES_ERROR'
export const FETCH_ADVANTAGES_SUCCESS = 'FETCH_ADVANTAGES_SUCCESS'

// dispatch professions
export const FETCH_PROFESSIONS_REQUEST = 'FETCH_PROFESSIONS_REQUEST'
export const FETCH_PROFESSIONS_ERROR = 'FETCH_PROFESSIONS_ERROR'
export const FETCH_PROFESSIONS_SUCCESS = 'FETCH_PROFESSIONS_SUCCESS'

// dispatch organizations
export const FETCH_ORGANIZATIONS_REQUEST = 'FETCH_ORGANIZATIONS_REQUEST'
export const FETCH_ORGANIZATIONS_ERROR = 'FETCH_ORGANIZATIONS_ERROR'
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS'

// dispatch
export const FETCH_CHARACTER_REQUEST = 'FETCH_CHARACTER_REQUEST'
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS'
export const FETCH_CHARACTER_ERROR = 'FETCH_CHARACTER_ERROR'


export const DELETE_CHARACTER = 'DELETE_CHARACTER'
export const CREATE_CHARACTER_CREATOR = 'CREATE_CHARACTER_CREATOR'

// auth login
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

// register
export const REG_SUCCESS = 'REG_SUCCESS'
export const REG_ERROR = 'REG_ERROR'