
export const DELETE_CHARACTER = 'DELETE_CHARACTER'
export const CREATE_CHARACTER_CREATOR = 'CREATE_CHARACTER_CREATOR'

// auth login and register
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'