export const FETCH_CHARACTER_START = 'FETCH_CHARACTER_START'
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS'
export const FETCH_CHARACTER_ERROR = 'FETCH_CHARACTER_ERROR'


export const DELETE_CHARACTER = 'DELETE_CHARACTER'
export const CREATE_CHARACTER_CREATOR = 'CREATE_CHARACTER_CREATOR'

// auth login
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

// register
export const REG_SUCCESS = 'REG_SUCCESS'
export const REG_ERROR = 'REG_ERROR'